// src/components/AgentResultPanel.tsx
// Renders any backend agent result with structured coloured sections,
// a compliance score badge, and PDF / Word / TXT export options.

'use client'

import { formatAgentResult } from '@/utils/formatAgentResult'
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
} from 'docx'

interface AgentResultPanelProps {
  result: Record<string, unknown>
  agentName: string
  agentId: string
  filename?: string
  onReset: () => void
}

export function AgentResultPanel({
  result,
  agentName,
  agentId,
  filename,
  onReset,
}: AgentResultPanelProps) {
  const formatted = formatAgentResult(result)
  const outputText = formatted.displayText
  const score = formatted.complianceScore

  // ── TXT export ─────────────────────────────────────────────────────────────
  const downloadTxt = () => {
    const header = [
      `RegCheck-India — ${agentName} Report`,
      `Document: ${filename ?? 'Unknown'}`,
      `Generated: ${new Date().toLocaleString('en-IN')}`,
      '─'.repeat(60),
      '',
    ].join('\n')
    const footer = [
      '',
      '─'.repeat(60),
      'All outputs require review by a qualified Regulatory',
      'Affairs professional before CDSCO submission.',
      'Generated by RegCheck-India v1.0 Beta',
    ].join('\n')
    const blob = new Blob([header + outputText + footer], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${agentName.replace(/\s+/g, '-')}-report.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  // ── Word (.docx) export ────────────────────────────────────────────────────
  const downloadDocx = async () => {
    const children: Paragraph[] = []

    children.push(
      new Paragraph({
        text: `${agentName} — Compliance Report`,
        heading: HeadingLevel.HEADING_1,
      }),
    )
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `Document: ${filename ?? 'Unknown'}   |   Generated: ${new Date().toLocaleString('en-IN')}`,
            size: 20,
          }),
        ],
        spacing: { after: 200 },
      }),
    )

    if (score !== undefined) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: `Compliance Score: ${score}%`, bold: true, size: 24 }),
          ],
          spacing: { before: 200, after: 200 },
        }),
      )
    }

    for (const section of formatted.sections) {
      if (section.items.length === 0) continue
      children.push(
        new Paragraph({
          text: section.title,
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 300, after: 100 },
        }),
      )
      for (const item of section.items) {
        children.push(
          new Paragraph({
            children: [
              new TextRun({ text: '• ', bold: true }),
              new TextRun({ text: item }),
            ],
            spacing: { after: 80 },
            indent: { left: 360 },
          }),
        )
      }
    }

    if (formatted.sections.length === 0) {
      outputText.split('\n').forEach((line) => {
        children.push(
          new Paragraph({
            children: [new TextRun({ text: line || ' ' })],
            spacing: { after: 60 },
          }),
        )
      })
    }

    children.push(new Paragraph({ text: '' }))
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: 'All AI outputs require review by a qualified Regulatory Affairs professional before CDSCO submission.',
            italics: true,
            size: 18,
            color: '666666',
          }),
        ],
      }),
    )

    const doc = new Document({
      creator: 'RegCheck-India',
      title: `${agentName} Report`,
      sections: [{ children }],
    })

    const buffer = await Packer.toBlob(doc)
    const url = URL.createObjectURL(buffer)
    const a = document.createElement('a')
    a.href = url
    a.download = `${agentName.replace(/\s+/g, '-')}-report.docx`
    a.click()
    URL.revokeObjectURL(url)
  }

  // ── PDF export (styled print window) ──────────────────────────────────────
  const downloadPdf = () => {
    const scoreHtml =
      score !== undefined
        ? `<div class="score">Compliance Score: ${score}%</div>`
        : ''

    const sectionsHtml =
      formatted.sections.filter((s) => s.items.length > 0).length > 0
        ? formatted.sections
            .filter((s) => s.items.length > 0)
            .map(
              (s) => `
            <h2 class="section-${s.severity ?? 'neutral'}">${s.title}</h2>
            <ul>${s.items.map((i) => `<li>${i}</li>`).join('')}</ul>
          `,
            )
            .join('')
        : `<pre>${outputText}</pre>`

    const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>${agentName} Report</title>
<style>
  @page { margin: 2cm; size: A4; }
  body { font-family: 'Segoe UI', Arial, sans-serif; font-size: 11pt; color: #1a1a2e; line-height: 1.6; }
  .header { border-bottom: 2px solid #1A56DB; padding-bottom: 12px; margin-bottom: 20px; }
  h1 { color: #1A56DB; font-size: 18pt; margin: 0 0 6px 0; }
  .meta { font-size: 9pt; color: #666; }
  .score { font-size: 14pt; font-weight: bold; color: #1A56DB; margin: 16px 0; padding: 10px 16px; background: #EBF5FF; border-radius: 6px; display: inline-block; }
  h2 { font-size: 12pt; margin: 20px 0 8px; padding: 6px 10px; border-radius: 4px; }
  .section-critical { background: #FEE2E2; color: #991B1B; }
  .section-major { background: #FEF3C7; color: #92400E; }
  .section-minor { background: #DBEAFE; color: #1E40AF; }
  .section-positive { background: #DCFCE7; color: #166534; }
  .section-neutral { background: #F3F4F6; color: #374151; }
  ul { margin: 0 0 12px 0; padding-left: 20px; }
  li { margin-bottom: 6px; font-size: 10.5pt; }
  pre { font-size: 9pt; white-space: pre-wrap; background: #F9FAFB; padding: 12px; border-radius: 4px; }
  .disclaimer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #e5e7eb; font-size: 9pt; color: #666; font-style: italic; }
  @media print { body { -webkit-print-color-adjust: exact; print-color-adjust: exact; } }
</style>
</head>
<body>
  <div class="header">
    <h1>${agentName} — Compliance Report</h1>
    <div class="meta">Document: ${filename ?? 'Unknown'} &nbsp;|&nbsp; Generated: ${new Date().toLocaleString('en-IN')} &nbsp;|&nbsp; RegCheck-India v1.0 Beta</div>
  </div>
  ${scoreHtml}
  ${sectionsHtml}
  <div class="disclaimer">All AI outputs require review by a qualified Regulatory Affairs professional before CDSCO submission.</div>
</body>
</html>`

    const printWindow = window.open('', '_blank')
    if (!printWindow) return
    printWindow.document.write(html)
    printWindow.document.close()
    printWindow.focus()
    setTimeout(() => { printWindow.print(); printWindow.close() }, 500)
  }

  const toggleExportMenu = () => {
    const el = document.getElementById(`export-menu-${agentId}`)
    if (el) el.style.display = el.style.display === 'none' ? 'block' : 'none'
  }

  // ── Render ──────────────────────────────────────────────────────────────────
  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>
      {/* Header */}
      <div
        style={{
          padding: '14px 16px',
          background: 'rgba(26, 86, 219, 0.05)',
          color: 'var(--rc-primary)',
          fontSize: 12.5,
          fontWeight: 600,
          borderBottom: '1px solid var(--rc-divider)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          gap: 8,
        }}
      >
        <div>
          <span style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
            <i className="ti ti-sparkles" />
            {agentName} — Analysis Complete
          </span>
          {filename && (
            <div style={{ fontSize: 11, color: 'var(--rc-text-muted)', marginTop: 2, fontWeight: 400 }}>
              {filename}
              {score !== undefined && (
                <span
                  style={{
                    marginLeft: 10,
                    fontWeight: 700,
                    color:
                      score >= 85
                        ? 'var(--rc-approved)'
                        : score >= 65
                        ? 'var(--rc-review)'
                        : 'var(--rc-rejected)',
                  }}
                >
                  {score}% compliant
                </span>
              )}
            </div>
          )}
        </div>

        <div style={{ display: 'flex', gap: 6, flexShrink: 0 }}>
          {/* Export dropdown */}
          <div style={{ position: 'relative' }}>
            <button className="rc-btn rc-btn-ghost rc-btn-sm" onClick={toggleExportMenu}>
              <i className="ti ti-download" /> Export
              <i className="ti ti-chevron-down" style={{ fontSize: 11, marginLeft: 4 }} />
            </button>
            <div
              id={`export-menu-${agentId}`}
              style={{
                display: 'none',
                position: 'absolute',
                top: 'calc(100% + 4px)',
                right: 0,
                background: 'var(--rc-surface)',
                border: '1px solid var(--rc-border)',
                borderRadius: 'var(--rc-radius)',
                boxShadow: 'var(--rc-shadow-md)',
                minWidth: 180,
                zIndex: 50,
              }}
            >
              {[
                { label: 'Download as PDF', icon: 'ti-file-type-pdf', action: downloadPdf },
                { label: 'Download as Word', icon: 'ti-file-type-docx', action: downloadDocx },
                { label: 'Download as TXT', icon: 'ti-file-text', action: downloadTxt },
              ].map((opt) => (
                <button
                  key={opt.label}
                  className="rc-nav-item"
                  style={{ width: '100%', justifyContent: 'flex-start' }}
                  onClick={() => {
                    opt.action()
                    const el = document.getElementById(`export-menu-${agentId}`)
                    if (el) el.style.display = 'none'
                  }}
                >
                  <i className={`ti ${opt.icon}`} style={{ marginRight: 8 }} />
                  {opt.label}
                </button>
              ))}
            </div>
          </div>

          <button className="rc-btn rc-btn-ghost rc-btn-sm" onClick={onReset}>
            <i className="ti ti-rotate" /> Run Again
          </button>
        </div>
      </div>

      {/* Main output */}
      <div className="rc-scroll" style={{ flex: 1, overflowY: 'auto', maxHeight: 500 }}>
        {formatted.sections.filter((s) => s.items.length > 0).length > 0 ? (
          <div style={{ padding: '0 14px 14px' }}>
            {formatted.sections.map((section, i) =>
              section.items.length === 0 ? null : (
                <div key={i} style={{ marginTop: 14 }}>
                  {/* Section heading */}
                  <div
                    style={{
                      fontSize: 11,
                      fontWeight: 700,
                      textTransform: 'uppercase',
                      letterSpacing: '0.05em',
                      marginBottom: 6,
                      color:
                        section.severity === 'critical'
                          ? 'var(--rc-rejected)'
                          : section.severity === 'major'
                          ? 'var(--rc-review)'
                          : section.severity === 'positive'
                          ? 'var(--rc-approved)'
                          : 'var(--rc-text-secondary)',
                    }}
                  >
                    {section.severity && section.severity !== 'positive' && (
                      <span
                        style={{
                          display: 'inline-block',
                          width: 8,
                          height: 8,
                          borderRadius: '50%',
                          background: 'currentColor',
                          marginRight: 6,
                        }}
                      />
                    )}
                    {section.title}
                  </div>

                  {/* Items */}
                  {section.items.map((item, j) => (
                    <div
                      key={j}
                      style={{
                        display: 'flex',
                        gap: 8,
                        padding: '7px 10px',
                        marginBottom: 4,
                        borderRadius: 'var(--rc-radius)',
                        background:
                          section.severity === 'critical'
                            ? 'var(--rc-rejected-bg)'
                            : section.severity === 'major'
                            ? 'var(--rc-review-bg)'
                            : section.severity === 'positive'
                            ? 'var(--rc-approved-bg)'
                            : 'var(--rc-surface-raised)',
                        fontSize: 12.5,
                        lineHeight: 1.5,
                        color: 'var(--rc-text-primary)',
                      }}
                    >
                      <span style={{ flexShrink: 0, marginTop: 1 }}>
                        {section.severity === 'critical'
                          ? '🔴'
                          : section.severity === 'major'
                          ? '🟡'
                          : section.severity === 'minor'
                          ? '🔵'
                          : section.severity === 'positive'
                          ? '✅'
                          : '•'}
                      </span>
                      <span>{item}</span>
                    </div>
                  ))}
                </div>
              ),
            )}
          </div>
        ) : (
          <pre
            style={{
              margin: 0,
              padding: 16,
              fontSize: 12,
              fontFamily: "var(--font-mono, 'Courier New', monospace)",
              whiteSpace: 'pre-wrap',
              wordBreak: 'break-word',
              lineHeight: 1.65,
              color: 'var(--rc-text-primary)',
            }}
          >
            {outputText}
          </pre>
        )}
      </div>

      {/* Disclaimer */}
      <div
        style={{
          padding: '10px 16px',
          fontSize: 11,
          color: 'var(--rc-text-muted)',
          fontStyle: 'italic',
          borderTop: '1px solid var(--rc-divider)',
        }}
      >
        All outputs require review by a qualified Regulatory Affairs professional before CDSCO submission.
      </div>
    </div>
  )
}
