export default function AIDisclaimer() {
  return (
    <div className="mt-6 px-4 py-3 rounded-xl bg-amber-500/5 border border-amber-500/20 flex items-start gap-3">
      <svg className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
      </svg>
      <div>
        <div className="text-xs font-semibold text-amber-400 mb-0.5">
          AI-Generated Output — Professional Review Required
        </div>
        <div className="text-xs text-slate-500 leading-relaxed">
          This output is generated by AI and may contain errors or omissions.
          It must be reviewed and validated by a qualified Regulatory Affairs professional
          before use in any regulatory submission to CDSCO or any other authority.
          RegCheck-India is a compliance support tool, not a substitute for professional regulatory advice.
        </div>
      </div>
    </div>
  )
}
